//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bebeclick.WebClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bebeclick.WebClient.Resources.Portal", typeof(Portal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Product_DuplicatedName {
            get {
                return ResourceManager.GetString("Product_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string Product_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("Product_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string Product_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("Product_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string Product_EmptyName {
            get {
                return ResourceManager.GetString("Product_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State ID must be set..
        /// </summary>
        internal static string Product_EmptyStateID {
            get {
                return ResourceManager.GetString("Product_EmptyStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Product_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("Product_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Product_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("Product_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string Product_MaxNameLength {
            get {
                return ResourceManager.GetString("Product_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Province_DuplicatedName {
            get {
                return ResourceManager.GetString("Province_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string Province_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("Province_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string Province_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("Province_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string Province_EmptyName {
            get {
                return ResourceManager.GetString("Province_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State ID must be set..
        /// </summary>
        internal static string Province_EmptyStateID {
            get {
                return ResourceManager.GetString("Province_EmptyStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Province_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("Province_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Province_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("Province_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string Province_MaxNameLength {
            get {
                return ResourceManager.GetString("Province_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Service_DuplicatedName {
            get {
                return ResourceManager.GetString("Service_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string Service_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("Service_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string Service_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("Service_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string Service_EmptyName {
            get {
                return ResourceManager.GetString("Service_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID must be set..
        /// </summary>
        internal static string Service_EmptyProductID {
            get {
                return ResourceManager.GetString("Service_EmptyProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Service_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("Service_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Service_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("Service_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string Service_MaxNameLength {
            get {
                return ResourceManager.GetString("Service_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &quot;{0}&quot; already exists..
        /// </summary>
        internal static string StateEntity_DuplicatedName {
            get {
                return ResourceManager.GetString("StateEntity_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string StateEntity_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("StateEntity_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string StateEntity_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("StateEntity_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string StateEntity_EmptyName {
            get {
                return ResourceManager.GetString("StateEntity_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string StateEntity_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("StateEntity_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string StateEntity_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("StateEntity_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string StateEntity_MaxNameLength {
            get {
                return ResourceManager.GetString("StateEntity_MaxNameLength", resourceCulture);
            }
        }
    }
}
